config/routes.rb
Rails.application.routes.draw do
    root 'products#index'
    resources :products, only: [:show]
    resources :charges
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
 # @product = Proudct.find(params[:id])
end

def create
  # Amount in cents
  #@product = Product.find(params[:id])
  @product = Product.find_by_id(session[:productid])
  @amount = (Integer(@product.price) * 100)
  
  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    session[:productid] = @product.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/create.html.erb
<h2>Thank you!</h2>
<p>Your donation of <strong><%= number_to_currency(@amount * 0.01) %></strong>
 has been received.</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $<%= @product.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @product.title %>"
          data-amount="<%= @product.price * 100 %> "
          data-locale="auto"
          data-billing-address="true"
          data-name="Blackdistressed"
          data-zip-code="true"
          data-image="http://i.imgur.com/9q9WhBF.png"
          ></script>
<% end %>

<style>
  .amount
  {
    font-size: 20px;
  }
</style>

app/views/layouts/_navigation.html.erb
<div class="container-fluid">
   <div class="row">
      <img src="http://placehold.it/450x200" class="img-responsive center-block">
   </div>
</div>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Products <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Contact</a></li>
         <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul> 
        </li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<style>
  .navbar-nav
  {
    font-size: 23px;
  }
  .navbar .navbar-nav {
    display: inline-block;
    float: none;
    vertical-align: top;
  }
  
  .navbar .navbar-collapse {
    text-align: center;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/picnicss/6.1.1/picnic.min.css"> -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navigation' %>
  <section class="main">
      <%= yield %>
  </section>
</body>
</html>

app/views/products/index.html.erb
<div class="row">
<% @products.each do |product| %>
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <img src="<%= product.picture %>" alt="...">
      <div class="caption">
        <h3><%= product.title %></h3>
        <h4>$<%= product.price %>0</h4>
        <%= link_to "Details", product_path(product), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/products/oldproducts.html.erb
<div class="flex one three-1000">
  <% @products.each do |product| %>
    <article class="card">
      <img src="<%= product.picture %>">
      <footer>
        <h3><%= product.title %></h3>
        <%= link_to "Deets", product_path(product), class: "button" %>
      </footer>
    </article>
  <% end %>
</div>

app/views/products/show.html.erb
<div class="container-fluid">
    <div class="container-fluid">
       <div class="row">
          <img src="<%= @product.picture %>" class="img-responsive" />
       </div>
    </div>
    <div class="row text-center">
      <div class="col-md-12">
        <h1><%= @product.title %></h1>
        <p>
          <%= @product.description %>
        </p>
  
        <!-- <h2><%= number_to_currency(@product.price) %></h2> -->
        <hr />
        <%= render :template => "charges/new" %> 
  
      </div>
    </div>
  </div>
<br>